#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 14 17:37:02 2023

@author: wmallard
"""
import sys
try:
    directories = sys.argv[1:]
    assert directories
except:
    script = sys.argv[0].split('/')[-1]
    print(f'Usage: {script} DIRECTORIES', file=sys.stderr)
    sys.exit(1)

import numpy as np
from pathlib import Path

from util import load_image
from util import save_stack

def process_images(directory):
    '''
    Infer how to process the TIFF stack based on the filenames.

    1. Delete thumbnails generated by MetaMorph.
    2. Confirm this is a timeseries.
    3. Detect if this is a multipoint timeseries,
       and if so, process each point separately.
    '''
    basedir = Path(directory)

    # Delete all thumbnails.
    thumbnails = basedir.glob('*_thumb_*.TIF')
    for src in thumbnails:
        src.unlink()

    # Decide how to process the directory based on the first TIFF file.
    is_timeseries = lambda path: path.match('*_t*.TIF')
    is_multipoint = lambda path: path.match('*_s[0-9]*.TIF')
    extract_FOV = lambda path: int(str(path).split('_s')[-1].split('_')[0])

    p = next(basedir.glob('*.TIF'))

    if not is_timeseries(p):
        print(' - Does not appear to be a timeseries. Skipping.')
        return

    if is_multipoint(p):
        FOVs = sorted(set(extract_FOV(path) for path in basedir.glob('*.TIF')))
        for n in FOVs:
            print(f'- field of view {n}')
            merge_timeseries_images(basedir, f'*_s{n}_t*.TIF')
    else:
        merge_timeseries_images(basedir, '*_t*.TIF')

def merge_timeseries_images(basedir, filename_pattern):
    '''
    Merge the timeseries into a TIFF stack.
    '''
    paths = basedir.glob(filename_pattern)

    # Sort list of files to merge.
    timestep = lambda path: int(path.stem.split('_t')[-1])
    paths = sorted(paths, key=timestep)
    files = [str(path) for path in paths]

    # Load images and merge into a tiff stack.
    im = np.stack([load_image(f) for f in files])

    # Construct output filename.
    p = paths[0]
    base = p.stem.rsplit('_t', 1)[0]
    stem = p.suffix.lower()
    outfile = basedir.parent / (base + stem)

    # Write to disk.
    save_stack(outfile, im)

for directory in directories:
    print(f'Processing: {directory}')
    process_images(directory)
